USE master;
GO
IF DB_ID(N'C2D5') IS NOT NULL BEGIN ALTER DATABASE C2D5 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D5; END
GO
CREATE DATABASE C2D5;
GO
USE C2D5;
GO
CREATE TABLE Estudiantes (IdEstudiante INT IDENTITY PRIMARY KEY, Nombre VARCHAR(80) NOT NULL);
CREATE TABLE Cursos (IdCurso INT IDENTITY PRIMARY KEY, Nombre VARCHAR(80) NOT NULL);
CREATE TABLE Inscripciones (IdEstudiante INT NOT NULL, IdCurso INT NOT NULL, Fecha DATE NOT NULL, PRIMARY KEY (IdEstudiante,IdCurso), FOREIGN KEY (IdEstudiante) REFERENCES Estudiantes(IdEstudiante), FOREIGN KEY (IdCurso) REFERENCES Cursos(IdCurso));
INSERT INTO Estudiantes VALUES ('Sofia'),('Mateo');
INSERT INTO Cursos VALUES ('SQL'),('C#'),('LINQ');
INSERT INTO Inscripciones VALUES (1,1,'2026-01-10'),(1,2,'2026-01-11'),(2,1,'2026-01-12');
GO