USE master;
GO
IF DB_ID(N'C2D3') IS NOT NULL BEGIN ALTER DATABASE C2D3 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D3; END
GO
CREATE DATABASE C2D3;
GO
USE C2D3;
GO
CREATE TABLE Clientes (IdCliente INT PRIMARY KEY, Nombre VARCHAR(80) NOT NULL);
CREATE TABLE Pedidos (IdPedido INT PRIMARY KEY, IdCliente INT NOT NULL, Total DECIMAL(10,2) NOT NULL, FOREIGN KEY (IdCliente) REFERENCES Clientes(IdCliente) ON DELETE CASCADE ON UPDATE CASCADE);
INSERT INTO Clientes VALUES (1,'Ana'),(2,'Luis');
INSERT INTO Pedidos VALUES (101,1,250),(102,1,80),(103,2,125);
GO