USE master;
GO
IF DB_ID(N'C2D10') IS NOT NULL BEGIN ALTER DATABASE C2D10 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D10; END
GO
CREATE DATABASE C2D10;
GO
USE C2D10;
GO
CREATE TABLE Clientes (Id INT PRIMARY KEY, Nombre VARCHAR(80), Ciudad VARCHAR(50));
CREATE TABLE Proveedores (Id INT PRIMARY KEY, Nombre VARCHAR(80), Ciudad VARCHAR(50));
INSERT INTO Clientes VALUES (1,'Ana','Bogota'),(2,'Luis','Cali');
INSERT INTO Proveedores VALUES (10,'Acme','Bogota'),(11,'Norte','Medellin');
GO