USE master;
GO
IF DB_ID(N'C2D11') IS NOT NULL BEGIN ALTER DATABASE C2D11 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D11; END
GO
CREATE DATABASE C2D11;
GO
USE C2D11;
GO
CREATE TABLE Facturas (IdFactura INT PRIMARY KEY, Fecha DATE NOT NULL);
CREATE TABLE Productos (IdProducto INT PRIMARY KEY, Nombre VARCHAR(80) NOT NULL, Precio DECIMAL(10,2) NOT NULL);
CREATE TABLE Detalles (IdDetalle INT PRIMARY KEY, IdFactura INT NOT NULL, IdProducto INT NOT NULL, Cantidad INT NOT NULL, FOREIGN KEY (IdFactura) REFERENCES Facturas(IdFactura), FOREIGN KEY (IdProducto) REFERENCES Productos(IdProducto));
INSERT INTO Facturas VALUES (100,'2026-02-01'),(101,'2026-02-02');
INSERT INTO Productos VALUES (10,'Teclado',50),(11,'Mouse',25),(12,'Monitor',180);
INSERT INTO Detalles VALUES (1,100,10,2),(2,100,11,1),(3,101,12,1);
GO