USE master;
GO
IF DB_ID(N'C2D12') IS NOT NULL BEGIN ALTER DATABASE C2D12 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D12; END
GO
CREATE DATABASE C2D12;
GO
USE C2D12;
GO
CREATE TABLE Clientes (IdCliente INT PRIMARY KEY, Nombre VARCHAR(80));
CREATE TABLE Pedidos (IdPedido INT PRIMARY KEY, IdCliente INT NOT NULL, Estado VARCHAR(20) NOT NULL, FOREIGN KEY (IdCliente) REFERENCES Clientes(IdCliente));
INSERT INTO Clientes VALUES (1,'Ana'),(2,'Luis'),(3,'Marta');
INSERT INTO Pedidos VALUES (101,1,'Pagado'),(102,1,'Pendiente'),(103,2,'Pagado');
GO