USE master;
GO
IF DB_ID(N'C2D8') IS NOT NULL BEGIN ALTER DATABASE C2D8 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D8; END
GO
CREATE DATABASE C2D8;
GO
USE C2D8;
GO
CREATE TABLE Clientes (IdCliente INT PRIMARY KEY, Nombre VARCHAR(80) NOT NULL);
CREATE TABLE Facturas (IdFactura INT PRIMARY KEY, IdCliente INT NOT NULL, Total DECIMAL(10,2) NOT NULL, FOREIGN KEY (IdCliente) REFERENCES Clientes(IdCliente));
INSERT INTO Clientes VALUES (1,'Ana'),(2,'Luis'),(3,'Marta');
INSERT INTO Facturas VALUES (101,1,200),(102,2,350);
GO