USE master;
GO
IF DB_ID(N'C2D2') IS NOT NULL BEGIN ALTER DATABASE C2D2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D2; END
GO
CREATE DATABASE C2D2;
GO
USE C2D2;
GO
CREATE TABLE Categorias (IdCategoria INT IDENTITY PRIMARY KEY, Nombre VARCHAR(60) NOT NULL);
CREATE TABLE Productos (IdProducto INT IDENTITY PRIMARY KEY, Nombre VARCHAR(80) NOT NULL, IdCategoria INT NOT NULL, FOREIGN KEY (IdCategoria) REFERENCES Categorias(IdCategoria));
INSERT INTO Categorias VALUES ('Libros'),('Papeleria');
INSERT INTO Productos VALUES ('SQL',1),('Cuaderno',2);
GO