USE master;
GO
IF DB_ID(N'C2D4') IS NOT NULL BEGIN ALTER DATABASE C2D4 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D4; END
GO
CREATE DATABASE C2D4;
GO
USE C2D4;
GO
CREATE TABLE Clientes (IdCliente INT IDENTITY PRIMARY KEY, Nombre VARCHAR(80) NOT NULL);
CREATE TABLE Facturas (IdFactura INT IDENTITY PRIMARY KEY, IdCliente INT NOT NULL, Fecha DATE NOT NULL, Total DECIMAL(10,2) NOT NULL, FOREIGN KEY (IdCliente) REFERENCES Clientes(IdCliente));
INSERT INTO Clientes VALUES ('Carla'),('Diego');
INSERT INTO Facturas VALUES (1,'2026-01-10',300),(1,'2026-02-10',125.50),(2,'2026-02-12',80);
GO