USE master;
GO
IF DB_ID(N'C2D1') IS NOT NULL BEGIN ALTER DATABASE C2D1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE C2D1; END
GO
CREATE DATABASE C2D1;
GO
USE C2D1;
GO
CREATE TABLE Clientes (IdCliente INT IDENTITY(1,1) PRIMARY KEY, Nombre VARCHAR(80) NOT NULL, Email VARCHAR(120) NOT NULL);
INSERT INTO Clientes (Nombre, Email) VALUES ('Ana','ana@email.com'),('Luis','luis@email.com');
GO